DATA_FOLDER = "/floyd/home/Data/"

TILES_FOLDER = DATA_FOLDER + "/tiles/PV/"

SAT_IMAGE_FOLDER = "/satellites/"
MASK_IMAGE_FOLDER = "/masks/"

TRAIN_IMAGE_FOLDER = TILES_FOLDER + "/train/"
TEST_IMAGE_FOLDER = TILES_FOLDER + "/test/"
TRAIN_TEST_RATIO = 0.2

WEIGHTS_FOLDER = DATA_FOLDER + "/weights/"
LOGS_FOLDER = DATA_FOLDER + "/logs/"

# Image size for VGG16
TILE_SIZE = (224,224)
